
CREATE USER appuser IDENTIFIED BY appuser;
GRANT UNLIMITED TABLESPACE to appuser;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW to appuser;

CREATE USER testuser IDENTIFIED BY testuser;
GRANT UNLIMITED TABLESPACE to testuser;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW to testuser;
EXIT;
